#! /usr/bin/env zsh

for file in ./zsh/boot_strap_functions/*; do
    source "$file"
done

_installer_log "Ensuring dot files are setup" "green" "bold"
INDENT="    "
source zsh/dot/dot.sh
dot_main set
INDENT=""

# zsh
setup_zsh $SYSTEM

# Programming languages
INDENT=""
_installer_log "🗣 Installing languages" "green" "bold"
INDENT="    "
setup_python
# coomand line
INDENT=""
_installer_log "👾 Command Line" "green" "bold"
INDENT="  "
_installer_log "🎨 Visual"
INDENT="      "
install_powerline
INDENT="  "
install_cli_essentials
INDENT="  "
_installer_log "🏃 Installing Command Line improvements"
INDENT="      "
install_bat
INDENT="  "
_installer_log "💪 Installing Command Line enhancers"
INDENT="      "
install_direnv
install_jump_tool
install_ripgrep

# GUI
INDENT=""
install_gui_programs $SYSTEM
