[tasks.update_brewfile]
description = "Update Brewfile from current Homebrew state"
run = [
  'rm Brewfile',
  'brew bundle dump',
  'git add -p Brewfile',
  'git commit -m "brew: update brewfile"'
]

[tasks.build]
description = "build nix"
run = [
  'nix run --extra-experimental-features nix-command --extra-experimental-features flakes nix-darwin -- build --flake ".#$(scutil --get ComputerName)"'
]
