#! /usr/bin/env zsh

source $HOME/.dotfiles/zsh/boot_strap_functions/helpers

_installer_log "Updating homebrew packages" "green" "bold"
_upgrade_brew_packages
_installer_log "Updating doom" "green" "bold"
doom upgrade -f
_installer_log "Updating dotfiles" "green" "bold"
~/.zsh/dot/dot.sh pull
dot set
_installer_log "Updating neovim" "green" "bold"
nvim --headless +PlugUpdate +q +q
