#!/usr/bin/env zsh
set -euo pipefail

line="$(
  rg --color=always \
     --colors 'path:none' --colors 'line:none' --colors 'column:none' \
     --line-number --no-heading --smart-case "${*:-}" |
  fzf --ansi \
    --delimiter : \
    --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
    --preview 'bat --color=always --highlight-line {2} -- {1}'
)" || exit 0

file="${line%%:*}"
rest="${line#*:}"
lnum="${rest%%:*}"

nvim "+${lnum}" -- "$file"
