#! /usr/bin/env zsh

IFS=: read -A selected < <(
  rg --color=always --line-number --no-heading --smart-case "${*:-}" |
	fzf --ansi \
		--color "hl:-1:underline,hl+:-1:underline:reverse" \
		--delimiter : \
		--preview 'bat --color=always {1} --highlight-line {2}' \
		--preview-window 'up,60%,border-bottom,+{2}+3/3,~3'
)
[ -n "${selected[1]}" ] && nvim "${selected[1]}" "+${selected[2]}"
