export BROWSER='open'
export PAGER='less'
SCRIPTPATH=$(readlink $HOME/.zshenv)
export DOTFILES_DIR=$(dirname -- "$(dirname -- $SCRIPTPATH)")
export ICLOUD_DIR=$(dirname -- $DOTFILES_DIR)

source $DOTFILES_DIR"/zsh/zsh_path"

#
# Language
#
if [[ -z "$LANG" ]]; then
    export LANG='en_US.UTF-8'
fi

#
# Temporary Files
#
if [[ ! -d "$TMPDIR" ]]; then
    export TMPDIR="/tmp/$LOGNAME"
    mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

source $DOTFILES_DIR"/zsh/zsh_ruby"
# Editors
export DEFAULT_USER='michael'
export EDITOR='nvim'
export BUNDLER_EDITOR='nvim'
export VISUAL='nvim'

source $DOTFILES_DIR"/zsh/zsh_aliases"


export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

# Programs

# fasd
eval "$(fasd --init auto)"

# Less
#
# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Use ripgrep to find files for fzf (respects gitignore)
export FZF_DEFAULT_COMMAND='rg --files'
